### ISSUE TITLE
Blurry Font with pdf-tools

### ISSUE THREAD

**Issue by rememberYou** [mpsq/emacs-gcc-wayland-devel-builder#1]
First of all, thank you for this package! 

I tested your package with `sway 1.5.1` (under Wayland) and GNU Emacs using `pdf-tools` to open my PDFs. However, I still have a blurry font (probably related to `pdf-tools`). Do you have this issue too?

**Comment by mpsq** [comment]
Hi Terencio,
I do not use `pdf-tools`, so I can't confirm. Going through their issues, there is something [that could be related](https://github.com/politza/pdf-tools/pull/469). Overall, I think this is not an Emacs problem but I could be wrong!

**Comment by rememberYou** [comment]
Thanks for the reply. 

I'm going to look to fix this 😊
