### ISSUE TITLE
White overlay on graphical emacs with transparency

### ISSUE THREAD

**Issue by CorentinCAM** [mpsq/emacs-gcc-wayland-devel-builder#20]
When I run emacs on graphical mode with transparency enabled, a white overlay appears and makes everything hard to read... Any idea what's happening here and how could I fix it?

OS: Arch
Compositor: sway
Emacs distribution: spacemacs

Screenshot:
![image](https://user-images.githubusercontent.com/26230177/114301020-1665c280-9ac3-11eb-80b5-d8fe8fac392b.png)

**Comment by mpsq** [comment]
How do you enable transparency. from Emacs itself?

**Comment by CorentinCAM** [comment]
Yes, like this:
`(set-frame-parameter (selected-frame) 'alpha '(90 . 90))
(add-to-list 'default-frame-alist '(alpha . (90 . 90)))`
or
`(spacemacs/enable-transparency)`

**Comment by mpsq** [comment]
This will probably not work, since you are using Sway you could simply do it there instead:

Sway config:

```
for_window [app_id="emacs"] opacity 0.9
```

**Comment by CorentinCAM** [comment]
I could, but this makes the whole thing transparent (even the font) which is not really what I'm looking for... But it will do the job while there is no other solution :slightly_smiling_face:
