### ISSUE TITLE
libjpeg.so.8: cannot open shared object file

### ISSUE THREAD

**Issue by niyumard** [mpsq/emacs-gcc-wayland-devel-builder#26]
On Gentoo I can't run the binaries and I get the following error even though I have media-libs/libjpeg-turbo installed with static-libs use flag.

`emacs: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory`

**Comment by mpsq** [comment]
This is because of glibc / symbol versioning. This should be fixed by updating the underlying libraries. The current package links to bleeding-edge versions because we use Arch under the hood.

**Comment by rbutoi** [comment]
Any tips on how to install this in Debian? [Looks like it was removed](https://bugs.debian.org/867047).

**Comment by plasticmae** [comment]
Seconding this, I'm having this issue.
