### ISSUE TITLE
Kill Ring not populated with Clipboard contents on Wayland Session

### ISSUE THREAD

**Issue by appetrosyan** [mpsq/emacs-gcc-wayland-devel-builder#8]
Hi. Not sure this is the right place, but the application when running as a Wayland native window (xeyes not moving) is unable to yank from the system clipboard. Tested on Plasma 5.21 wayland session

This kind of defeats the purpose of even using this build, as clipboard management is a pretty big omission that **is** present in the regular native-comp version.

**Comment by mpsq** [comment]
This works just fine for me, I am using Sway though, not Plasma.

> This kind of defeats the purpose of even using this build, as clipboard management is a pretty big omission that is present in the regular native-comp version.

This package does not amend, patch, or tweak the sources before compiling Emacs. The upstream base branch is NOT "native-comp" though, it is "pgtk-nativecomp", you can find it [here](https://github.com/flatwhatson/emacs#branch=pgtk-nativecomp). What you are experiencing is most likely a bug with Plasma or the upstream branch.

**Comment by appetrosyan** [comment]
I must apologise, the issue seems to be related more to KDE, than to emacs.
